#!/usr/bin/env bash

# This script uses CUPS to configure the printing defaults for the HP printer
# drivers for HP multifunction copiers/printers. It was designed to work on
# macOS with the HP Color LaserJet Managed Flow MFP E77830.
#
# To see all the CUPS printer options: lpoptions -l

set -e

drivername="HP Color MFP E77822-25-30"
lpinfo --make-and-model "$drivername" -m > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "Error: $drivername printer driver missing"
  exit 1
fi

echo
printf "\e[1mCUPS printer names:\e[0m\n"; lpstat -a | cut -f1 -d ' '; echo


printf "\e[1mWhich one is the HP E77830?\e[0m "
read -e
printername="$REPLY"
echo

printf "\e[1mDefault to grayscale?\e[0m [Y/n] "
read -e
colorentry="$REPLY"

HPColorAsGray="BlackInkOnly"  # default to grayscale
if [[ "$colorentry" = "n" ]]; then
  echo "Defaulting to color."
  HPColorAsGray="None"
fi
echo

set -o xtrace
lpadmin -p "$printername" -o Duplex=DuplexNoTumble \
                          -o MediaType=Plain \
                          -o HPEasyColor=False \
                          -o HPColorAsGray=$HPColorAsGray
set +o xtrace

printf "\n\e[1mDone!\e[0m\n\n"
