#!/usr/bin/env bash
set -e

echo
printf "\e[1mCUPS printer names:\e[0m\n"; lpstat -a | cut -f1 -d ' '; echo


printf "\e[1mWhich one is the HP E77830?\e[0m "
read -e
printername="$REPLY"
echo

printf "\e[1mDefault to grayscale?\e[0m [Y/n] "
read -e
colorentry="$REPLY"

HPColorAsGray="BlackInkOnly"  # default to grayscale
if [[ "$colorentry" = "n" ]]; then
  echo "Defaulting to color."
  HPColorAsGray="None"
fi
echo

set -o xtrace
lpadmin -p "$printername" -o Duplex=DuplexNoTumble \
                          -o MediaType=Plain \
                          -o HPEasyColor=False \
                          -o HPColorAsGray=$HPColorAsGray
set +o xtrace

printf "\n\e[1mDone!\e[0m\n\n"
